---
- name: "compose : Check current docker-compose version"
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: "compose : Delete existing docker-compose version if it's different"
  become: true
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: "compose : Install Docker Compose via Github (if configured)"
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755
  when: not docker_support_ansible

- name: "compose : Install Docker Compose via Pip (if configured)"
  become: true
  pip:
    name: docker-compose
    state: latest
  when: docker_support_ansible
