##
# Author: Dan Kempster
# License: MIT - provided at end of file
#
---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  become: true
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

# TODO: Remove this shim once 18.09.1 or later is released.
- import_tasks: shims/docker-1809-shim.yml
  when: ansible_service_mgr == 'systemd'

- name: main | Secure Docker with certificates
  import_tasks: "certs.yml"
  notify:
    - "restart docker"
  when: docker_generate_certs

- name: "main : ensure Docker users are configured"
  include_tasks: users.yml

- name: "main : ensure support for anisble docker modules"
  include_tasks: ansible.yml
  when: docker_support_ansible

- name: "main | ensure docker-compose is installed"
  include_tasks: compose.yml
  when: docker_install_compose
