---
- name: Ensure old versions of Docker are not installed.
  become: true
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present

- name: Add Docker apt key.
  become: true
  apt_key:
    url: "https://download.docker.com/linux/\
      {{ (ansible_lsb.id | default(ansible_distribution)) | lower }}\
      /gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add Docker repository.
  become: true
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
